#! /bin/sh

# $1: hex file basname
# $2: path to project (top qbs file path)

#post_compile:
$2/qbs/tools/teensy_post_compile -file="$1" -path="$2/build/" -tools="$2/qbs/tools"

#reboot:
$2/qbs/tools/teensy_reboot